version: "3.8"

services:
  sftp-blobfuse:
    image: oh22/sftp-blobfuse:latest
    restart: always
    container_name: sftp-blobfuse
    security_opt:
      - apparmor:unconfined
    cap_add:
      - "SYS_ADMIN"
    devices:
      - "/dev/fuse:/dev/fuse"
    ports:
      - "2222:22/tcp"
    environment:
      - AZURE_STORAGE_ACCOUNT="<Storage Account Name>"
      - AZURE_STORAGE_ACCESS_KEY="<Storage Account Access Key>"
      - AZURE_STORAGE_ACCOUNT_CONTAINER="<Storage Account Container>"
      - AZURE_MOUNT_POINT="/home/foo/mount"
      - SFTP_USERS="foo:password"